eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/
# 若需要实现服务降级需要将当前参数由false改为true
feign:
  hystrix:
    enabled: true

logging:
  level:
    io.seata.sample: DEBUG
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: io.seata.sample.entity
server:
  port: 8980
spring:
  application:
    name: order-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/seat-order
    username: root

# 需要新增的配置
seata:
  tx-service-group: fsp_tx_group
  registry:
    eureka:
      service-url: http://localhost:9090/eureka
      application: seata-demo
    type: eureka
  service:
    vgroup-mapping: seata-demo
    disable-global-transaction: false



# 增加ribbon和hystrix的配置将他们的超时时间设置的长一点，可能是我电脑比较垃圾，因此执行一次完整的链路时间需要好几秒，因此在默认不配置以下参数的时候会导致我的链路请求超时导致失败而回滚，因此我增加了以下的配置。
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 12000
  ConnectTimeout: 12000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 设置断路器超时时间
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 490000
          strategy: SEMAPHORE

