eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:9090/eureka/
# 配置日志信息
logging:
  level:
    io.seata.sample: DEBUG
# 配置mybatis的相关扫描的位置
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: io.seata.sample.entity
server:
  port: 8181
spring:
  application:
    name: account-server
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 575088Wl
    url: jdbc:mysql://47.105.71.151:3306/seat-account
    username: root

# 需要新增的配置
seata:
  # 对应seata-server的file.conf中的service底下的vgroup_mapping的后缀的值
  tx-service-group: fsp_tx_group
  service:
    # 对应seata-registry.conf中的eureka底下的application的值
    vgroup-mapping: seata-demo
    disable-global-transaction: false
  registry:
    type: eureka
    eureka:
      service-url: http://localhost:9090/eureka


# 增加ribbon和hystrix的配置将他们的超时时间设置的长一点，可能是我电脑比较垃圾，因此执行一次完整的链路时间需要好几秒，因此在默认不配置以下参数的时候会导致我的链路请求超时导致失败而回滚，因此我增加了以下的配置。
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 12000
  ConnectTimeout: 12000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  OkToRetryOnAllOperations: false
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 设置断路器超时时间
hystrix:
  threadpool:
    default:
      coreSize: 1000
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 490000
          strategy: SEMAPHORE

